### ISSUE TITLE
Construir a aplicação localmente

### ISSUE THREAD

**Issue by BlaserLuken** [BlaserLuken/javaee7-petclinic#2]

**Comment by fabiohsalmeida** [comment]
Na execução desta tarefa foram utilizadas as ferramentas **git-bash** e **IDE Eclipse Mars**.

**Baixando artefato do repositório**
Passo 1: Criar uma pasta em algum diretório desejado.
Passo 2: Abrir o prompt na pasta destino.
Passo 3: Escrever o comando `git clone https://github.com/BlaserLuken/javaee7-petclinic.git`
Passo 4: Aguardar finalização do download do artefato.

**Importando para a IDE Eclipse**
Passo 1: Abrir Eclipse.
Passo 2: Clicar em `File -> Import -> Maven -> Existing Maven Projects`.
Passo 3: Selecionar pasta raiz onde foi realizado o clone do artefato.
Passo 4: Aguardar finalização do import, isso pode levar alguns minutos.

**Gerando artefato WAR**
Passo 1: Clicar com o botão direito no projeto.
Passo 2: Clicar em "Run As"
Passo 3: Clicar em "Maven Build..."
Passo 4: Selecionar a aba JRE e verificar se está utilizando um JDK e não um JRE.
Passo 5: Ir até a aba main
Passo 6: Preencher o campo "goal" com `clean install`
Passo 7: Clicar "Run"
Passo 8: Aguardar a finalização do build, deve ser informado `BUILD SUCCESS` ao fim da execução
Passo 9: Clicar o botão F5 com o projeto selecionado
Passo 10: Deve haver um arquivo .war no diretório `/target/`
